site_name: pbipinspect
site_description: Parse, validate and document your Power BI Project
repo_name: pbipinspect

theme: 
  name: "material"
  logo: assets/imgs/logo.svg
  favicon: assets/imgs/logo.svg
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference

extra_css:
  - css/style.css

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - "Home": 
    - "Home": index.md
    - "Changelog": changelog.md
    - "License": license.md
  - "Reference": reference

plugins:
  - search
  - include_dir_to_nav
  - mkdocstrings:
      handlers: 
        python:
          options:
            filters:
            - ""
            docstring_style: numpy
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            merge_init_into_class: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true

markdown_extensions:
- attr_list
- admonition
- footnotes
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.inlinehilite:
    style_plain_text: python
- pymdownx.magiclink
- pymdownx.snippets:
    base_path: [!relative $config_dir]
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
